### PR TITLE
Major Improvements; .NET Core, versions up, drop dependencies, and more!

### PR DESCRIPTION
**Pull request by DavidRieman**
I've finally carved out a big enough block of time to tackle some of the intertwined major upgrades we've been needing for a while.  This is still a work in progress, but in case anyone is lurking here, here are some of the bigger improvements:
* #52: Moved projects to simpler project file format, and then .NET Core!
* Only one solution platform target is used any more; Any CPU.
* #54: Recreated all package references to latest .NET Core versions, including ServiceStack.  The set of ServiceStack references was successfully minimized (after a long fight).
* #55: Taking latest System.Management (MEF) version.
* #43, #47: This got us a much-needed RavenDB upgrade, including fixing a security vulnerability.  Saving and loading players is working even better now.
* #53: Dropped Nini dependency; all app configuration is handled consistently through App.config now.
* #10: Dropped NVelocity dependency; view rendering is done through C# Renderer exports now, allowing for step-through debugging, unit testing, etc.  (WIP: There are still some renderers which need to be re-implemented and their old template files deleted.)
* #60: Dropped log4net which wasn't being used and massively bloated our App.config.
* Dropped other unused DLLs.
* #42: Dropped CodeSmith dependency / related files.  Relational entity records were given a base class and dropped 'partials' to simplify them down to a manually-sustainable state, especially as most of the entities should move to the document DB in the future.
* #58: Moved ServerHarness admin commands to be composed through MEF; Added ability to list all the admin commands and their descriptions.
* #59: Progress towards ServerHarness Shutdown command succeed gracefully.
* Fixed some miscellaneous Actions and bugs.
* Cleanup.

Leaving this in Draft for now, until I get another block of time to repair remaining renderers, finish removing their old template files, identifying and fixing anything else I meant to only temporarily break during the .NET Core upgrade.

### CODE REVIEW

**Comment by duaneking** [comment]
I thought this was dead due to the license being overly restrictive?

**Comment by DavidRieman** [comment]
What was dead?

**Comment by duaneking** [comment]
I'm talking about this project's use of MS-PL.

MS themselves states publicly not to use MS-PL.

We cant change the license unless we get sign off from everybody who has committed code, and that's impossible, But it also greatly limits what we can use in terms of dependencies etc due to the licensing issues

This is why I have not been working on it; Every time I get the urge to do so I'm reminded that the license is the sort that even MS themselves say not to use.

**Comment by DavidRieman** [comment]
> MS themselves states publicly not to use MS-PL

That seems like the sort of thing that should be easy to find articles talking about.  Can you provide a link?

Personally I do not feel that Ms-PL is restrictive, nor feel the need for it to be a dead end.  For example, I could absolutely run a commercial MUD build on this code base, if I so choose, some day.

I thought we resolved this back at #6 - then again when it came back at #33 I asked if you could _open a new thread to discuss what scenario you feel is important that you feel restricted from_ but I'm not finding any example yet - did I miss happen to miss something?  Do you have a specific library or whatnot that you want to use but feel we can't?  If you're still living/working in Seattle area, would you like to catch up and discuss offline over a lunch or something?

**Comment by duaneking** [comment]
I thought we talked about this when we got coffee in Seattle last, feels like years ago?

Simply put,; .Net Core is MIT and Core is the future.  I'm worried that we can't use MSPL code with MIT code due to what I was told by a lawyer a bit back after #6 as the MSPL's restrictions are not MIT Compatible, is what I was told, so in my mind, if code is MSPL then it cant legally be used with MIT licensed code such as .Net Core or be brought forward and dso doesn't have a long term viability.  And when I last worked in Redmond, I was explicitly told by a legal professional that worked for the company not to use MSPL for open source.  I think that's why my team at MSR used MIT for their client libs, and so that's what I used when I contributed to them.  It was just standard to use MIT.

I'm not a Lawyer. I don't play one on TV.  I studied Law for like a year and got as far as contract and torts before switching to software because I realized that the law was not my passion, but I'm still very much under the impression that the MSPL isn't even used by Microsoft anymore as it's overly restrictive and would complicate the ability to use backend open source databases or libs that people actually want to use due to limited licensing restrictions that no would allow MIT and GPL* licensed frameworks to be leveraged.

I'm also under the impression that is actually why the dependency tree is so weird, here licensing issues that mean we can't use the tech we want to use due to incompatible licenses and further complicate past arcitectual issues.  If thas not the case would love to understand that better.

**Comment by DavidRieman** [comment]
Ahh, if that was part of our conversation all those years ago, I can honestly say I don't remember any of that - I barely remember any of it.  There had been other reasons blocking and demotivating me from contributing, so if this was ever one of the factors, I had completely forgotten.

Hmm, my initial impression was that our use of NuGet dependencies is using _compiled binaries_, and as such, I thought that we don't have the copyleft effect trying to flow the license to those binaries.  I will have to do some more thinking on this and do some more research and such.  Thank you for your eloquent response.

**Comment by DavidRieman** [comment]
The more I read, re-read and research, the more I'm sure the way we make use of MIT libraries is not a problem for us.  Obviously I'm not a lawyer either.  I'm feeling comfortable with proceeding with using .NET Core though, and _especially_ comfortable with _dropping_ the usage of all the dependencies that I dropped.  :)

One thing I did identify as a potential help (even though we aren't technically redistributing MIT code or packages, we're using NuGet to point at such packages), was to add a copy of the MIT license and point out we're making use of those libs.  I've pushed up new license text files to help clarify where we're at.

**Comment by DavidRieman** [comment]
Marked as ready for review.  I think I've left the code much better off that it started, and looking forward to closing quite a few of the linked issues.

**Comment by DavidRieman** [comment]
Any further thoughts coming?

**Comment by DavidRieman** [comment]
Switched back to a model where I target my base repository, while I wait for further response here.

FWIW this code base has long used MEF binaries, being a set of files which AFAICT have always been built from source code that was written on MIT, so going to .NET Core binaries isn't exactly a change in consumption model, so much as adopting more of the existing consumption model?

**Comment by duaneking** [comment]
Any reason why I'm getting an email about this just as I get a surprise email about being removed from the wheelmud org?

**Comment by DavidRieman** [comment]
I'm simplifying the WheelMUD repo stack to a single space.  I've set up Projects and such on the base repo and want to simplify recent confusion about which repo should get forked.  This repo has gotten stale.  The organization hasn't been performing as expected anymore.  E.G. this PR has sat open for most of a year, and has zero responses my last 5 messages.

**Comment by DavidRieman** [comment]
I've merged the last open PR to clean up, to have the tab show zero pending PRs.  I will be updating the home page readme to explain we should just use the base repo, but are reserving this space for possible future usage, if code flow needs and contribution levels rise again.

**Comment by duaneking** [comment]
You never reached out or asked for any input; and it's common decency for us to close our own stale issues so we didn't think about it. Part of having the group and us staying in it was the expectation  that we would be pinged  when we were needed or there was an interesting idea we could work on together. Respectfully, That never happened from you. Having the PR open by itself was never something that was supposed to bring attention before, there's always been a very casual expectation around that; If things have changed, great, but let's do that together as a team. Especially since my domains and my work are still referenced and some of my ideas are the basis of a few things still in use.

**Comment by DavidRieman** [comment]
> You never reached out or asked for any input

Reaching out 5 times most of a year ago and getting no response, gave me no reason to believe you would be responsive and reasonable this time.

**Comment by duaneking** [comment]
With respect, you haven't reached out even once. The last time you and I talked we had coffee in person in Seattle years ago.

**Comment by DavidRieman** [comment]
In this very thread, I reached out on Feb 25, Feb 26, Mar 1, Mar 7, and Mar 22, all with zero responses.  I'm not sure why you went dark.

**Comment by duaneking** [comment]
I was hit by a car on October 1, 2019 but I have not received any attempts to communicate from you, and either it could be my injuries or the looking for work, but respectfully, I don't have a record of anything from you on these dates.

**Comment by DavidRieman** [comment]
I am sorry for your misfortune.  Unfortunately, if you can't figure out how you received none of my pings from this very PR thread that we are typing on now, I have no reason to believe that further PR requests _will_ actually get your attention and timely discussion / approval.  Thus, this is a major reason the org isn't working.  Maybe it will work better to just have contributors attached to the base repo that I had to resort to advancing alone.  Please understand that I bear no ill will to you, just that the org itself causing code stasis is the main thing I'm trying to fix here.  Incoming contributor confusion on where to fork from is the other main factor.

**Comment by duaneking** [comment]
So from my perspective, after having gone through my cell phone text message records at these times, looking at the historical record, you never reached out.

Another problem here is I contributed code and the new license file you edited says "the dev team" and doesn't attribute me for my past architectural and other code work unless I'm on the dev team. And its ambiguous.  The dev team its based on or the dev team of the PR?,  Honestly, I should still remain on the dev team as I worked on the project, either way.

Otherwise the license just got a lot more complicated. Its not a personal thing, But I see this as you kicking me out of a club I worked hard to support, stayed with longer than most when everybody else dropped out, that uses my past work, and now you do not want to attribute that work in violation of the license, despite he fact that you opening this PR was not an official ping by you when you and I made a separate personal agreement that you would text me when we had coffee together for big things like it.  You never did that. You never reached out and I have the cell phone records to prove it.  You cant say you can't assume I would not respond when you never tried to reach out.  I expected you to text me, because we had coffee in person and you said you would, and you said that like a friend.

Literally, the README for the project uses my domain gamedev.com, it talks about my documentation, about my architecture, I designed, the notes I took, etc.  This is as much my project as anybody else's.

**Comment by duaneking** [comment]
In addition, a PR is a PULL Request. It is not a Pull Demand.  If you need urgency on an issue you could have pinged me directly, something many other developers on github don't enjoy the freedom to do.  I make my twitter (honestduane), my keybase (dfk), my counetersocial (dk) etc all known and people have just followed me on keybase or reached out and said hello and I never even had coffee with them, so what was stopping you when you had my number, knew my name, etc?  You never mentioned me explicitly.

**Comment by duaneking** [comment]
I am asking to be re-added to the team, as thats only fair given my history on it.

**Comment by DavidRieman** [comment]
Funny enough, just earlier before all this today, I had noticed the defunct domain reference and cleaned that out while pointing at the newly opened GitHub Discussions area for fresh WheelMUD dialog.  These changes couldn't flow through this direction though due to PR stasis.  I'm preparing a fresh PR to take the latest from the base repo though, including that cleanup and new clarification on top of the commonplace OSS "the dev team" level of attribution (and other changes accumulated since the previous PR).

It was not my intent to appear to be kicking you out. You have my sincere apologies for that. Your entry in the WheelMUD team list suggested your presence was "private" so I didn't realize that this even had any impact on your apparent online presence here. (I wonder if GitHub has a bug on this or if I just misunderstand what that flag does?)  I should have reached out to try to check on that too.

Now that I understand it was meaningful even with a "private" membership flag, of course I'll re-invite you to the org.  Indeed you deserve to be listed in this org team if you want to be!  Of course you still show up as a contributor on the active base repo, too.  :)

**Comment by duaneking** [comment]
I don't know how my profile was marked as private or what that does.

Thank you for the invite back in, as well as for the additional clarification.

In the future, please don't hesitate to @duaneking at me and if you want to ping me over twitter or something I can give you my contact data again if you have lost it.  I'm rebuilding my life, looking for work, and dealing with zoom funerals like everybody else, but this project has always been dear to me.

**Pull request merged**
