### PR TITLE
Combining TestHarness and WindowsService projects. Issues/15.

### PR DESCRIPTION
**Pull request by DavidRieman**
- Moved Topshelf logic into the TestHarness. TODO: Renaming TestHarness project/namespaces should probably follow.
- Removes the old WindowsService and housing solution folder.
- Adds Topshelf package to source control, and removed packages from .gitignore; Reduces the number of sites that have
  to be online in order to get and build source successfully. (We've been bitten by offline/rogue nugets before.)
- If run without arguments, TestHarness runs in the normal interactive mode, else runs in Topshelf/service mode.
- Simplified that assembly name to "WheelMUD.exe"

### CODE REVIEW

**Comment by duaneking** [comment]
Why the removal of the binary file ignore? Topshelf is open source and freely available; it also gets bug fixes for free if we don't include it in binary form and just use the nuget.. needless to say I'm against checking in binaries :(

**Comment by DavidRieman** [comment]
I'll post my response here: http://muds.gamedev.com/mudforum/index.php?t=msg&goto=484

In short, it reduces points of failure and thus increases success rate during source evaluation.

**Comment by Thraka** [comment]
Why not link to the **specific** nuget package instead of **latest**? Then you just update when you need to, verifying that specific version is compatible.

**Comment by DavidRieman** [comment]
Welcome!  Yes the usefulness and ease of the process you mention is perhaps the best aspect of NuGet.  Our packages already do specify specific versions to protect us from breaking changes.

The question here is actually whether it is best to have the binaries checked in.  Checking them in does not remotely break the safe NuGet upgrade process.  It does however reduce the number of points of failure (download sites) required to be communicative in order to succeed at the moment of First Build, which is very important for that first impression.  That's a great place to reduce the number of points of failure, IMO.

**Comment by Thraka** [comment]
Hi. I used to play around with the WheelMUD guys like... 8 years ago or something.. Thought I would come check it out again.

I do understand the point you're making, but going the extra mile to prevent an edge case that probably won't appear for the majority of developers, doesn't seem really worth it. I feel like in my experience it's standard practice **not** to include nuget-retrieved binaries, and only to include non-nuget.

Also, Visual Studio doesn't seem to add them to git when you add a nuget reference, it only adds/updates the config.

Glad to meet you guys :smile_cat:

**Comment by DavidRieman** [comment]
The notion of not checking in rapidly changing binaries has been around since HD space was expensive.  I'm simply challenging whether that notion is appropriate for the general case anymore, let alone for infrequently-changing, small, absolutely-required dependencies.

It's not an extra mile to check them in; more like an extra inch IMO.

The issue is not actually a big deal for me, either way;  I'd be happy to back down on this in the end.  I just think it's an interesting conversation, and looking forward to anyone stating an actual _reason_ to avoid putting binaries in that is still valid in modern day.  So... anything other than "because tradition" or "a small amount of HD space"  :)

FWIW, everywhere I've worked the last decade usually checked in all dependencies except truly massive installers, whether they were acquired through NuGet or otherwise.  With a notable exception where our interpretation of the security agreements of the dependency forbade us from doing so.

**Comment by dr-ratio** [comment]
Bump?

**Pull request merged**
