### PR TITLE
Update .gitignore to standard gitup .net .gitignore plus the custom item...

### PR DESCRIPTION
**Pull request by duaneking**
...s required by the wheelmud build system.

### CODE REVIEW

**Comment by duaneking** [comment]
I could have just merged this in but lets use githubs merge requests so we can keep updated on what each other is adding, OK? 

Besides, it makes it more social and public that we are actually trying to improve this code base a bit and add features.

**Comment by DavidRieman** [comment]
Agreed.

**Comment by duaneking** [comment]
Merge when you want to, just push the button and it goes into the wheelmud orgs copy..

Push the button... you know you want to..

**Comment by DavidRieman** [comment]
Can you give me access to accept pull requests so I can accept yours?

**Comment by DavidRieman** [comment]
Aha, I think it was that mobile failed to join the org when I followed the invite.  This morning on PC I found that I wasn't joined yet.  Pulled!

**Comment by duaneking** [comment]
That was 8.5 thousand lines of dead code removed even when you count my additions.  Think about that.  I'm sure more exists..

**Pull request merged**
